# Generated by Django 3.1.2 on 2020-10-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderaccounts',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='traderaccounts',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='traderaccounts',
            name='trader',
        ),
        migrations.DeleteModel(
            name='BaseCurrency',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='TraderAccounts',
        ),
    ]
