# Generated by Django 3.1.2 on 2020-10-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanguser',
            name='email',
        ),
    ]
