# Generated by Django 3.1.2 on 2020-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hanguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
