# Generated by Django 3.1.2 on 2020-10-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkexPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('trader_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trader.traderaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='KucoinPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('trader_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trader.traderaccounts')),
            ],
        ),
    ]
