# Generated by Django 3.1.2 on 2020-11-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_kucoinpassword_okexpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderaccounts',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='traderaccounts',
            name='shrimpy_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='traderaccounts',
            name='shrimpy_secret_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='traderaccounts',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('account_balance', models.FloatField(blank=True, null=True)),
                ('trader_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trader.traderaccounts')),
            ],
        ),
    ]
