# Generated by Django 3.1.2 on 2020-11-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20201105_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderaccounts',
            name='password',
        ),
        migrations.RemoveField(
            model_name='traderaccounts',
            name='shrimpy_api_key',
        ),
        migrations.RemoveField(
            model_name='traderaccounts',
            name='shrimpy_secret_key',
        ),
    ]
